---
title: Architect theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Architect is a theme for GitHub Pages.
show_downloads: true
google_analytics: 
theme: jekyll-theme-architect
