---
title: NATION 66
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Crypto Governance, Free Your Nation
show_downloads: false
theme: jekyll-theme-architect
