---
title: NATION 66
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Crypto Governance, Own Your Nation
show_downloads: false
google_analytics: 
theme: jekyll-theme-architect
